### PR TITLE
.NET Core 1.0 Upgrade

### PR DESCRIPTION
**Pull request by PaddoSwam**
Breaking change in respect to Legacy calls, made them `throw new NotImplentedException` and upgraded the whole project to be more in line of .NET Core 1.0 (1.1) projects.

### CODE REVIEW

**Comment by dazinator** [comment]
Wow, thanks a lot for this. I'll give this a review.

**Comment by dazinator** [comment]
In general, this looks great!
I'm thinking of setting up an AppVeyor build process once this PR is merged.
Can you just talk me through the removal of webengine4.dll in terms of, do you know what the ramifications of removing this is? I have an old legacy cookie produced by an asp.net 3.5 website, and after these change - nothing seems to be impacted - the cookie can still be decrypted, and a new cookie can be encrypted and all seems to work fine. So at the moment, I am thinking there should be no real loss or impact in terms of removing webengine.dll - would you agree?

**Comment by PaddoSwam** [comment]
I've verified that my use case was covered, .NET 3.5 FormsAuthentication encrypted cookie based on AES and SHA1 validation keys and found no issues. I also have a piece of Middleware to use this package in ASP.NET Core MVC/WebApi projects

**Comment by dazinator** [comment]
LGTM

**Comment by dazinator** [comment]
One minor thing, is that i'll be converting the library project form a netcore app 1.0 project, to a `netstandard` library project instead. This will allow any platform that supports netstandard (which includes netcoreapp applications) to consume the library. Without this, only netcore applications can consume the library. [More info on that here if interested](https://github.com/dotnet/cli/issues/3647)

**Comment by PaddoSwam** [comment]
I can only agree with that, great idea!

**Pull request merged**
