### PR TITLE
Fix #20: UTC vs Local DateTime

### LINKED ISSUE #20: UTC vs LocalTime in FormsAuthenticationTicket
The code to serialize and deserialize the `FormsAuthenticationTicket` assumes the data in `FormsAuthenticationTicket` for issue and expiration dates to be local DateTimes.

In ASP.Net old code:
https://github.com/microsoft/referencesource/blob/master/System.Web/Security/FormsAuthenticationTicketSerializer.cs:

`Serialize` has code `ticketWriter.Write(ticket.IssueDateUtc.Ticks);` and `ticketWriter.Write(ticket.ExpirationUtc.Ticks);`
`Deserialize` calls `FormsAuthenticationTicket.FromUtc`

In AspNetCore.LegacyAuthCookieCompat (class `FormsAuthenticationTicketHelper`):

`Serialize` has code `ticketWriter.Write(ticket.IssueDate.ToUniversalTime().Ticks);` and `ticketWriter.Write(ticket.Expiration.ToUniversalTime().Ticks);`
`Deserialize` calls `FormsAuthenticationTicketHelper.FromUtc`

Moreover, in old ASP.Net code, `FormsAuthenticationTicket.FromUtc` converts the `issueDateUtc` and `expirationUtc` to local time with `.ToLocalTime()` (https://github.com/microsoft/referencesource/blob/master/System.Web/Security/FormsAuthenticationTicket.cs#L228-L229)

This last step isn't done in AspNetCore.LegacyAuthCookieCompat (See https://github.com/dazinator/AspNetCore.LegacyAuthCookieCompat/blob/master/src/AspNetCore.LegacyAuthCookieCompat/FormsAuthenticationTicketHelper.cs#L129-L131).

Because of this, the issue date and expiration date of deserialized tickets is never the correct one, as it will always be UTC.

Tests didn't catch that because they incorrectly create `FormsAuthenticationTicket` with UTC DateTime instead of local ones and didn't double check the date from the tickets deserialized from legacy ASP.Net serialization.

This is a major issue as tickets will have an extended or shortened lifetime depending on which side of UTC we are.

I will be preparing a pull request fixing these issues.

### PR DESCRIPTION
**Pull request by lemoinem**
Here is the fix for #20
I tweaked the test a little bit so we don't run into this kind of issue in the future.

This is really a major issue for us.
Once merged, would it be possible to push a new version to NuGet ASAP?

### CODE REVIEW

**Comment by dazinator** [comment]
Thanks for the PR. Yep I'll get this pushed tomorrow morning.

**Comment by dazinator** [comment]
Just so I understand this correctly, a quick question:

Does this mean in scenario where there is legacy site A, and a .net core site B:

1. Server A sets expiry date and issue date using its local time zone. When it receives a request with it's own cookie, the data is parsed using its local time zone (DateTimeKind.Local) and comparison behaves as expected.

2. Server A redirects to Server B. Suppose server B has different local time zone to server A. Server B parses expiry and issue date as "Local" and then converts to UTC for comparison. If the time zone of server B is different from server A, the issue date may be in the future, and IdValid check will fail?

Therefore for SSO to work accross both sites, they must both use same local time zone?

**Comment by lemoinem** [comment]
The datetime is save as UTC Ticks in the Cookies, but are stored as local DateTime in the FormsAuthenticationTicket. The conversion is done at deserialization time (this is the step that was missing).

Even if both servers have different timezones, this wouldn't be an issue, as the time is still serialized as UTC Ticks in the Cookie. Any timezone conversion is local to each server.

Why it was implemented in this way instead of using UTC all the time is, quite frankly, beyond me. But that's the way legacy ASP.Net works...

**Comment by dazinator** [comment]
Thanks for the explanation.

I've merged, after verifying the tests all run locally for me. I've tagged master so the next release will be v2.0.0 to take into account this could be a breaking change in behaviour I thought the major version bump was warranted.

One thing though - even though the tests all pass locally for me, for some reason the test fails on the appveyor server: https://ci.appveyor.com/project/dazinator/aspnetcore-legacyauthcookiecompat

I can only think it must be something to do with local time and regional settings? If you have a moment would you be able to look into the failing test - as that's the only thing that is stopping the build from successfully completing and a new nuget package being pushed out!

**Comment by lemoinem** [comment]
@dazinator Thanks!

I had a look at the AppVeyor failure.
I've provided a new PR using a non-strict comparison in IsValid. I hope this solves the issue.
There are more details in the new PR.

**Pull request merged**
