### PR TITLE
Add ASP.Net 4.5 Compatibility

### LINKED ISSUE #9: asp.net 4.5
Hi - I am using this package to generate a encrypted cookie value and match the value created in ASP.NET 4.5. Is ASP.NET 4.5 is supported by this library ? Please advice.

### PR DESCRIPTION
**Pull request by lemoinem**
Fixes #9
I've kept the default compatibility mode to Framework20SP2, as that's basically what it was before.

All tests are green. I've added new tests for Framework45. I've done my best to respect the code style.
Please tell if anything needs to be changed.

### CODE REVIEW

**Comment by lemoinem** [comment]
PS: AppVeyor fails linked to missing `%signingkey%` config. I believe it's unrelated to my changes.

**Comment by dazinator** [comment]
Thanks for this. Yeah ignore the appveyor failure its not set up properly to deal with PR builds for this project. I'll review and merge - as long as there are no breaking changes introduced then I'll probably merge within next few days.

**Comment by lemoinem** [comment]
Hello,
It's been almost two weeks... Any news? Did you have the time to take a look at it? Is there anything I could do for the PR to go forward?
I'd very much prefer to be able to switch to a new version before I'm switching to something else.

**Comment by dazinator** [comment]
Hello - yeah sorry on holiday at the moment - back monday so will take a look then sorry for the delay :-)

**Comment by lemoinem** [comment]
No problem! Enjoy your holiday!

**Comment by lemoinem** [comment]
@dazinator Great news! Here is the updated README.md

**Comment by lemoinem** [comment]
@dazinator Thanks for the merge!
Would you mind publishing a new version to NuGet so we can start using this right away and remove our custom overriding code?

**Comment by dazinator** [comment]
It has published but it looks like the branch name has confused gitversion, and it calculated 4.5.0 as the next package version number. I might just leave it like that to be honest- you should find 4.5.0 on nuget.org (it takes a little while for nuget to validate)

**Comment by dazinator** [comment]
@lemoinem as per above this was pushed accidentally as package version 4.5.0 (gitversion issue) - I have just tagged it 1.3.0 and have triggered a push to nuget so it should appear shortly under the correct sem ver of 1.3.0. At which point I will unlist 4.5.0 on nuget.

**Pull request merged**
